spring:
  application:
    name: pensionMatching
  datasource:
    url: jdbc:mysql://localhost:3306/lottery?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: 1234
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
  kafka:
    bootstrap-servers: 192.168.0.20:9092
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  port: 8082

token:
  secret: "guess_secretguess_secretguess_secretguess_secret"